name: "CI: testing"

on:
  pull_request:
  push:
    branches-ignore:
      - "feature"

jobs:
  sonar: # sonar job is to setup and run sonar scan analysis on telematic cloud messaging code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetchepth: 0 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 18
      - name: Run test and generate coverage
        run: |
            cd $GITHUB_WORKSPACE/backend/http-server-js/foo
            npm install
            npm run coverage     
      - name: Find lcov.info
        shell: bash
        run: |
          find "$GITHUB_WORKSPACE" -name "lcov.info"   
      - name: Generate sonar properties file
        run: |
          cat <<EOF > /tmp/sonar-scanner.properties
            sonar.host.url=${{ secrets.SONAR_URL }}
            sonar.login=${{ secrets.SONAR_TOKEN }}
            sonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            sonar.sources=$GITHUB_WORKSPACE
            sonar.javascript.lcov.reportPaths=./coverage/lcov.info
            sonar.modules=foo
            foo.sonar.projectBaseDir=backend/http-server-js/foo
            foo.sonar.sources=.
            foo.sonar.exclusions=test/**
            foo.sonar.tests=test/
          EOF
      # Setup sonar-scanner
      - name: Run SonarScanner
        uses: warchant/setup-sonar-scanner@v7
        with:
          sonar-properties-path: /tmp/sonar-scanner.properties
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          working-dir: $GITHUB_WORKSPACE
            