name: "CI: testing"

on:
  pull_request:
  push:
    branches-ignore:
      - "feature"

jobs:
  sonar: # sonar job is to setup and run sonar scan analysis on telematic cloud messaging code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/demo/demo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 18
      - name: Run test and generate coverage
        run: | 
            ls -a
            cd $GITHUB_WORKSPACE/backend/http-server-js/foo
            npm install
            npm run coverage   
      - name: Find lcov.info
        shell: bash
        run: |
          find "$GITHUB_WORKSPACE" -name "lcov.info"   
      - name: Find properties
        shell: bash
        run: |
          find "$GITHUB_WORKSPACE" -name "sonar-scanner.properties"   
      
      # Setup sonar-scanner
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
            projectBaseDir: ./